server:
  port: ${PORT:8081}

spring:
  application:
    name: ms_backend_api

  datasource:
    url: jdbc:h2:mem:telecomdb;DB_CLOSE_DELAY=-1;MODE=MySQL
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  sql:
    init:
      mode: always

  h2:
    console:
      enabled: true
      path: /h2

msauth:
  base-url: ${MSAUTH_BASE_URL:http://localhost:8080}

jwt:
  secret: ${JWT_SECRET:mi_clave_super_segura_jwt_2026_1234567890}