server:
  port: ${PORT:8081}

spring:
  datasource:
    url: jdbc:h2:file:/tmp/telecomdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

h2:
  console:
    enabled: true
    path: /h2-console

msauth:
  base-url: ${MSAUTH_BASE_URL:https://ms-auth-2w01.onrender.com}

jwt:
  secret: ${JWT_SECRET:12345678901234567890123456789012}