INSERT INTO linea_diagnostico_consolidado (numeroTelefono,
                                           bscs_perfilPlanComercial, bscs_imei, bscs_marca, bscs_modelo,
                                           bscs_serieOriginal,
                                           hss_estadoRedVoz, hss_vlrRegistrada, hss_paisOperador, hss_redRegistrada,
                                           hss_disponibilidad,
                                           hss_ultimaCelda, hss_accesible, hss_fechaRegistro, hss_rnc,
                                           redviva_estadoRedDatos, redviva_ultimoNERegistrado,
                                           redviva_paisOperadorDatos, redviva_ultimaRedRegistrada,
                                           redviva_ultimaCeldaDatos, redviva_ultimoRegistroConexion, redviva_apnUso,
                                           redviva_ipApn,
                                           redviva_condicionVolte, redviva_anclajeVolte, redviva_enrutamientoVolte,
                                           redviva_volte, redviva_roamingVolte4G,
                                           pcrf_estadoIMEI, pcrf_condicionIMEI, pcrf_tecnologiaActiva,
                                           pcrf_planComercial, pcrf_estadoServicios,
                                           pcrf_vozWifi, pcrf_servicioDatos, pcrf_serviciosBasicos, pcrf_saldo,
                                           pcrf_serviciosSuplementarios,
                                           pcrf_serviciosAdicionales, pcrf_apnAprovisionados, pcrf_portabilidad)
VALUES ('51937232864',
        'Plan Abierto (No en ICC)', '3568454658755', 'Apple', 'iPhone 13', 'Entel_GUL',
        'Registrado', '51981500001', 'Perú/Entel', '3G', 'Disponible para llamadas',
        '01326303_LM_GONZALES_PRADA_R1', 'Alcanzable', TIMESTAMP '2026-02-21 17:21:46', 'LMPCSRNC7',
        'Registrado con datos desactivado', 'LIM_SBO_VUSN', 'Perú/Entel', '5G',
        '01726302_LM_Gonzales_Prada_R1', TIMESTAMP '2026-02-21 17:36:42', 'ENTEL.PE', '100.82.250.102',
        'No homologado', 'No configurado', 'No configurado', 'No configurado', 'Configurado',
        'Lista blanca', 'OK', '2G/3G/4G/5G', 'Plan Abierto (No en ICC)', 'Activo',
        'No Provisionado', 'Ver detalle', 'Habilitados', 'Ver detalle', 'Habilitados',
        'Configurado', 'Configurado', 'Nativo en Entel');

INSERT INTO linea_diagnostico_consolidado (numeroTelefono,
                                           bscs_perfilPlanComercial, bscs_imei, bscs_marca, bscs_modelo,
                                           bscs_serieOriginal,
                                           hss_estadoRedVoz, hss_vlrRegistrada, hss_paisOperador, hss_redRegistrada,
                                           hss_disponibilidad,
                                           hss_ultimaCelda, hss_accesible, hss_fechaRegistro, hss_rnc,
                                           redviva_estadoRedDatos, redviva_ultimoNERegistrado,
                                           redviva_paisOperadorDatos, redviva_ultimaRedRegistrada,
                                           redviva_ultimaCeldaDatos, redviva_ultimoRegistroConexion, redviva_apnUso,
                                           redviva_ipApn,
                                           redviva_condicionVolte, redviva_anclajeVolte, redviva_enrutamientoVolte,
                                           redviva_volte, redviva_roamingVolte4G,
                                           pcrf_estadoIMEI, pcrf_condicionIMEI, pcrf_tecnologiaActiva,
                                           pcrf_planComercial, pcrf_estadoServicios,
                                           pcrf_vozWifi, pcrf_servicioDatos, pcrf_serviciosBasicos, pcrf_saldo,
                                           pcrf_serviciosSuplementarios,
                                           pcrf_serviciosAdicionales, pcrf_apnAprovisionados, pcrf_portabilidad)
VALUES ('51987654321',
        'Postpago 79.90', '359999999999999', 'Samsung', 'Galaxy S23', 'Entel_GUL',
        'Registrado', '51981500002', 'Perú/Entel', '4G', 'Disponible',
        '01320001_LM_SURCO_R2', 'Alcanzable', TIMESTAMP '2026-03-01 10:10:00', 'LMPCSRNC8',
        'Registrado', 'LIM_MME_01', 'Perú/Entel', '5G',
        '01720001_LM_SURCO_R2', TIMESTAMP '2026-03-01 10:15:00', 'ENTEL.PE', '10.10.25.11',
        'Homologado', 'Configurado', 'Correcto', 'Activo', 'Configurado',
        'Lista blanca', 'OK', '4G/5G', 'Postpago 79.90', 'Activo',
        'Provisionado', 'Activo', 'Habilitados', '120.50', 'Habilitados',
        'Configurado', 'Configurado', 'Nativo en Entel');

INSERT INTO linea_diagnostico_consolidado (numeroTelefono,
                                           bscs_perfilPlanComercial, bscs_imei, bscs_marca, bscs_modelo,
                                           bscs_serieOriginal,
                                           hss_estadoRedVoz, hss_vlrRegistrada, hss_paisOperador, hss_redRegistrada,
                                           hss_disponibilidad,
                                           hss_ultimaCelda, hss_accesible, hss_fechaRegistro, hss_rnc,
                                           redviva_estadoRedDatos, redviva_ultimoNERegistrado,
                                           redviva_paisOperadorDatos, redviva_ultimaRedRegistrada,
                                           redviva_ultimaCeldaDatos, redviva_ultimoRegistroConexion, redviva_apnUso,
                                           redviva_ipApn,
                                           redviva_condicionVolte, redviva_anclajeVolte, redviva_enrutamientoVolte,
                                           redviva_volte, redviva_roamingVolte4G,
                                           pcrf_estadoIMEI, pcrf_condicionIMEI, pcrf_tecnologiaActiva,
                                           pcrf_planComercial, pcrf_estadoServicios,
                                           pcrf_vozWifi, pcrf_servicioDatos, pcrf_serviciosBasicos, pcrf_saldo,
                                           pcrf_serviciosSuplementarios,
                                           pcrf_serviciosAdicionales, pcrf_apnAprovisionados, pcrf_portabilidad)
VALUES ('51984561234',
        'Prepago', '358888888888888', 'Xiaomi', 'Redmi Note 12', 'Entel_GUL',
        'Registrado', '51981500003', 'Perú/Entel', '3G', 'Disponible',
        '01320002_LM_CALLAO_R3', 'Alcanzable', TIMESTAMP '2026-03-02 11:40:00', 'LMPCSRNC9',
        'Registrado', 'LIM_MME_02', 'Perú/Entel', '4G',
        '01720002_LM_CALLAO_R3', TIMESTAMP '2026-03-02 11:45:00', 'ENTEL.PE', '10.55.12.45',
        'Homologado', 'Configurado', 'Correcto', 'Activo', 'Configurado',
        'Lista blanca', 'OK', '3G/4G', 'Prepago', 'Activo',
        'No Provisionado', 'Activo', 'Habilitados', '15.20', 'Habilitados',
        'Configurado', 'Configurado', 'Portado');

INSERT INTO linea_diagnostico_consolidado (numeroTelefono,
                                           bscs_perfilPlanComercial, bscs_imei, bscs_marca, bscs_modelo,
                                           bscs_serieOriginal,
                                           hss_estadoRedVoz, hss_vlrRegistrada, hss_paisOperador, hss_redRegistrada,
                                           hss_disponibilidad,
                                           hss_ultimaCelda, hss_accesible, hss_fechaRegistro, hss_rnc,
                                           redviva_estadoRedDatos, redviva_ultimoNERegistrado,
                                           redviva_paisOperadorDatos, redviva_ultimaRedRegistrada,
                                           redviva_ultimaCeldaDatos, redviva_ultimoRegistroConexion, redviva_apnUso,
                                           redviva_ipApn,
                                           redviva_condicionVolte, redviva_anclajeVolte, redviva_enrutamientoVolte,
                                           redviva_volte, redviva_roamingVolte4G,
                                           pcrf_estadoIMEI, pcrf_condicionIMEI, pcrf_tecnologiaActiva,
                                           pcrf_planComercial, pcrf_estadoServicios,
                                           pcrf_vozWifi, pcrf_servicioDatos, pcrf_serviciosBasicos, pcrf_saldo,
                                           pcrf_serviciosSuplementarios,
                                           pcrf_serviciosAdicionales, pcrf_apnAprovisionados, pcrf_portabilidad)
VALUES ('51922541335',
        'Postpago 129.90', '357777777777777', 'Motorola', 'Edge 40', 'Entel_GUL',
        'No Registrado', NULL, 'Perú/Entel', 'Sin Red', 'No disponible',
        NULL, 'No Alcanzable', NULL, NULL,
        'No Registrado', NULL, 'Perú/Entel', 'Sin Red',
        NULL, NULL, NULL, NULL,
        'No homologado', 'No configurado', 'Incorrecto', 'Inactivo', 'No configurado',
        'Lista negra', 'Bloqueado', '4G/5G', 'Postpago 129.90', 'Suspendido',
        'Provisionado', 'Restringidos', 'Deshabilitados', '0.00', 'Deshabilitados',
        'No configurado', 'No configurado', 'Nativo en Entel');